# Generated by Django 3.1.1 on 2020-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
